[metadata]
creation_date = "2022/05/17"
maturity = "production"
updated_date = "2022/05/17"
integration = "kubernetes"

[rule]
author = ["Elastic"]
description = """
This rule detects a user attempting to access either one or all Kubernetes secrets within a given namespace, through a Kubernetes API server request. Kubernetes secrets often hold sensitive information, including credentials. Actions taken to gather credentials to container and cloud infrastructure can allow for privilege escalation within Kubernetes and access to external systems. 
"""
false_positives = [
    """
    An administrator may need to access secrets for a legitimate purpose.
    """,
]
index = ["filebeat-*", "logs-kubernetes.*"]
language = "kuery"
license = "Elastic License v2"
name = "Kubernetes Secrets Accessed"
note = """## Config

The Kubernetes Fleet integration with Audit Logs enabled, Filebeat module, or similarly structured data is required to be compatible with this rule."""
references = ["https://kubernetes.io/docs/concepts/configuration/secret/", 
"https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/"]
risk_score = 47
rule_id = "42e58833-f15b-4306-a8fb-a50f9526b605"
severity = "medium"
tags = ["Elastic", "Kubernetes", "Continuous Monitoring", "Credential Access"]
timestamp_override = "event.ingested"
type = "query"

query = '''
event.dataset : "kubernetes.audit_logs" and kubernetes.audit.objectRef.resource : "secrets" and kubernetes.audit.verb : ("get" or "list")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"

[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[[rule.threat.technique]]
id = "T1552"
name = "Unsecured Credentials"
reference = "https://attack.mitre.org/techniques/T1552/"
    
    [[rule.threat.technique.subtechnique]]
    id = "T1552.007"
    name = "Container API"
    reference = "https://attack.mitre.org/techniques/T1552/007/"

