[metadata]
creation_date = "2022/05/03"
maturity = "production"
updated_date = "2022/05/03"

[rule]
author = ["Elastic"]
description = """
Identifies Linux binary byebug absue to break out from restricted environments by spawning an interactive system shell.
The byebug utility is a Ruby debugger which provides various debugging capabilities for Ruby program and the activity of
spawning shell is not a standard use of this binary for a user or system administrator. It indicates a potentially
malicious actor attempting to improve the capabilities or stability of their access.
"""
from = "now-9m"
index = ["logs-endpoint.events.*"]
language = "eql"
license = "Elastic License v2"
name = "Linux Restricted Shell Breakout via byebug Shell Evasion"
references = ["https://gtfobins.github.io/gtfobins/byebug/"]
risk_score = 47
rule_id = "5611593e-fb75-4e1f-8859-b34f47babd83"
severity = "medium"
tags = ["Elastic", "Host", "Linux", "Threat Detection", "Execution", "GTFOBins"]
timestamp_override = "event.ingested"
type = "eql"

query = '''
process where event.type == "start" and process.name in ("bash", "sh", "dash") and process.parent.name == "byebug"
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[rule.threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"



[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

