[metadata]
creation_date = "2022/05/03"
maturity = "production"
updated_date = "2022/05/03"

[rule]
author = ["Elastic"]
description = """
Identifies Linux binary capsh abuse to break out from restricted environments by spawning an interactive system shell.
The capsh utility is a Linux tool tool provides a handy wrapper for certain types of capability testing and environment
creation and the activity of spawning shell is not a standard use of this binary for a user or system administrator. It
indicates a potentially malicious actor attempting to improve the capabilities or stability of their access.
"""
from = "now-9m"
index = ["logs-endpoint.events.*"]
language = "eql"
license = "Elastic License v2"
name = "Linux Restricted Shell Breakout via capsh Shell Evasion"
references = ["https://gtfobins.github.io/gtfobins/capsh/"]
risk_score = 47
rule_id = "030ae380-3f25-4185-8d24-03f5edc08997"
severity = "medium"
tags = ["Elastic", "Host", "Linux", "Threat Detection", "Execution", "GTFOBins"]
timestamp_override = "event.ingested"
type = "eql"

query = '''
process where event.type == "start" and process.name == "capsh" and process.args =="--"
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[rule.threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"



[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

